In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel(
    r"E:\Regional Sales Dataset.xlsx",
    sheet_name="Sales Orders"
)

In [ ]:
print("First 5 Rows:")
df.head()

First 5 Rows:

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270

In [ ]:
print("Last 5 Rows:")
df.tail()

Last 5 Rows:

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost
64099,SO - 0007573,2018-02-28,74,Wholesale,USD,AXW291,825,26,12,1815.7,21788.4,980.478
64100,SO - 0007706,2018-02-28,51,Export,USD,NXH382,444,21,6,864.3,5185.8,579.081
64101,SO - 0007718,2018-02-28,136,Distributor,USD,AXW291,312,13,11,3953.0,43483.0,2648.510
64102,SO - 0008084,2018-02-28,158,Distributor,USD,AXW291,737,20,7,3959.7,27717.9,2930.178
64103,SO - 0008654,2018-02-28,22,Distributor,USD,AXW291,807,15,8,998.3,7986.4,848.555

In [ ]:
print("Shape of Dataset:")
print(df.shape)

Shape of Dataset:
(64104, 12)

In [ ]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['OrderNumber', 'OrderDate', 'Customer Name Index', 'Channel',
       'Currency Code', 'Warehouse Code', 'Delivery Region Index',
       'Product Description Index', 'Order Quantity', 'Unit Price',
       'Line Total', 'Total Unit Cost'],
      dtype='object')

In [ ]:
print("Dataset Information:")
df.info()

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer Name Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency Code              64104 non-null  object
 5   Warehouse Code             64104 non-null  object
 6   Delivery Region Index      64104 non-null  int64
 7   Product Description Index  64104 non-null  int64
 8   Order Quantity             64104 non-null  int64
 9   Unit Price                 64104 non-null  float64
 10  Line Total                 64104 non-null  float64
 11  Total Unit Cost            64104 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(4), object(4)
memory usage: 5.9+ MB

In [ ]:
print("Summary Statistics (Numerical Columns):")
df.describe()

Summary Statistics (Numerical Columns):

,OrderDate,Customer Name Index,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost
count,64104,64104.000000,64104.000000,64104.000000,64104.000000,64104.000000,64104.000000,64104.000000
mean,2016-01-29 01:28:20.935979008,87.480064,495.086609,14.913141,8.441689,2284.380803,19280.682937,1432.083899
min,2014-01-01 00:00:00,1.000000,1.000000,1.000000,5.000000,167.500000,837.500000,68.675000
25%,2015-01-13 00:00:00,45.000000,247.000000,6.000000,6.000000,1031.800000,8019.900000,606.216000
50%,2016-01-27 00:00:00,87.000000,493.000000,15.000000,8.000000,1855.900000,14023.100000,1084.495500
75%,2017-02-13 00:00:00,130.000000,742.000000,24.000000,10.000000,3606.275000,27416.400000,2046.933750
max,2018-02-28 00:00:00,175.000000,994.000000,30.000000,12.000000,6566.000000,78711.600000,5498.556000
std,NaN,49.884946,285.645893,8.787032,2.276217,1663.598141,15429.602766,1107.705728

In [ ]:
print("Summary Statistics (Categorical Columns):")
df.describe(include='object')

Summary Statistics (Categorical Columns):

        OrderNumber    Channel Currency Code Warehouse Code
count         64104      64104         64104          64104
unique        10684          3             1              4
top     SO - 000225  Wholesale           USD         AXW291
freq              6      34596         64104          30204

In [ ]:
print("Missing Values Before Cleaning:")
print(df.isnull().sum())

Missing Values Before Cleaning:
OrderNumber                  0
OrderDate                    0
Customer Name Index          0
Channel                      0
Currency Code                0
Warehouse Code               0
Delivery Region Index        0
Product Description Index    0
Order Quantity               0
Unit Price                   0
Line Total                   0
Total Unit Cost              0
dtype: int64

In [ ]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df))*100
})

print(missing)

                           Missing Values  Percentage
OrderNumber                             0         0.0
OrderDate                               0         0.0
Customer Name Index                     0         0.0
Channel                                 0         0.0
Currency Code                           0         0.0
Warehouse Code                          0         0.0
Delivery Region Index                   0         0.0
Product Description Index               0         0.0
Order Quantity                          0         0.0
Unit Price                              0         0.0
Line Total                              0         0.0
Total Unit Cost                         0         0.0

In [ ]:
print("Duplicate Rows Before Cleaning:")
print(df.duplicated().sum())

Duplicate Rows Before Cleaning:
0

In [ ]:
df.drop_duplicates(inplace=True)

print("Duplicate Rows After Cleaning:")
print(df.duplicated().sum())

Duplicate Rows After Cleaning:
0

In [ ]:
print("Data Types:")
print(df.dtypes)

Data Types:
OrderNumber                          object
OrderDate                    datetime64[ns]
Customer Name Index                   int64
Channel                              object
Currency Code                        object
Warehouse Code                       object
Delivery Region Index                 int64
Product Description Index             int64
Order Quantity                        int64
Unit Price                          float64
Line Total                          float64
Total Unit Cost                     float64
dtype: object

In [ ]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"])

In [ ]:
categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    print(f"\nUnique values in {col}:")
    print(df[col].unique())

Unique values in OrderNumber:
['SO - 000225' 'SO - 0003378' 'SO - 0005126' ... 'SO - 0005376'
 'SO - 0010690' 'SO - 0009753']

Unique values in Channel:
['Wholesale' 'Distributor' 'Export']

Unique values in Currency Code:
['USD']

Unique values in Warehouse Code:
['AXW291' 'NXH382' 'GUT930' 'FLR025']

In [ ]:
for col in categorical_columns:
    df[col] = df[col].str.strip()

In [ ]:
for col in categorical_columns:
    df[col] = df[col].str.title()

In [ ]:
numeric_columns = df.select_dtypes(include=np.number).columns

for col in numeric_columns:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].median())

In [ ]:
for col in categorical_columns:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
print("Missing Values After Cleaning:")
print(df.isnull().sum())

Missing Values After Cleaning:
OrderNumber                  0
OrderDate                    0
Customer Name Index          0
Channel                      0
Currency Code                0
Warehouse Code               0
Delivery Region Index        0
Product Description Index    0
Order Quantity               0
Unit Price                   0
Line Total                   0
Total Unit Cost              0
dtype: int64

In [ ]:
df.columns = df.columns.str.strip().str.replace(" ", "_")

In [ ]:
print(df.columns)

Index(['OrderNumber', 'OrderDate', 'Customer_Name_Index', 'Channel',
       'Currency_Code', 'Warehouse_Code', 'Delivery_Region_Index',
       'Product_Description_Index', 'Order_Quantity', 'Unit_Price',
       'Line_Total', 'Total_Unit_Cost'],
      dtype='object')

In [ ]:
print("Final Dataset Information:")
df.info()

Final Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer_Name_Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency_Code              64104 non-null  object
 5   Warehouse_Code             64104 non-null  object
 6   Delivery_Region_Index      64104 non-null  int64
 7   Product_Description_Index  64104 non-null  int64
 8   Order_Quantity             64104 non-null  int64
 9   Unit_Price                 64104 non-null  float64
 10  Line_Total                 64104 non-null  float64
 11  Total_Unit_Cost            64104 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(4), object(4)
memory usage: 5.9+ MB

In [ ]:
df.head()

,OrderNumber,OrderDate,Customer_Name_Index,Channel,Currency_Code,Warehouse_Code,Delivery_Region_Index,Product_Description_Index,Order_Quantity,Unit_Price,Line_Total,Total_Unit_Cost
0,So - 000225,2014-01-01,126,Wholesale,Usd,Axw291,364,27,6,2499.1,14994.6,1824.343
1,So - 0003378,2014-01-01,96,Distributor,Usd,Axw291,488,20,11,2351.7,25868.7,1269.918
2,So - 0005126,2014-01-01,8,Wholesale,Usd,Axw291,155,26,6,978.2,5869.2,684.740
3,So - 0005614,2014-01-01,42,Export,Usd,Axw291,473,7,7,2338.3,16368.1,1028.852
4,So - 0005781,2014-01-01,73,Wholesale,Usd,Axw291,256,8,8,2291.4,18331.2,1260.270

In [ ]:
df.to_csv("Cleaned_Regional_Sales.csv", index=False)

print("Cleaned dataset saved successfully as CSV.")

Cleaned dataset saved successfully as CSV.

In [33]:
df.to_excel("Cleaned_Regional_Sales.xlsx", index=False)

print("Cleaned dataset saved successfully as Excel.")

Cleaned dataset saved successfully as Excel.

In [34]:
print("="*50)
print("DATA CLEANING COMPLETED")
print("="*50)

print("Final Shape :", df.shape)
print("Remaining Missing Values :", df.isnull().sum().sum())
print("Remaining Duplicate Rows :", df.duplicated().sum())

==================================================
DATA CLEANING COMPLETED
==================================================
Final Shape : (64104, 12)
Remaining Missing Values : 0
Remaining Duplicate Rows : 0